version:  "3"
services:
  database:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    ports:
      - "3308:3306"
    expose:
      - 3306
    volumes: 
      - ./database:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  api:
    build: ./api
    ports:
      - "3001:3000"
    depends_on:
      - database
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME} 
  users:
    build: ./users
    ports:
      - "3002:3000"
    depends_on:
      - database
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}  
  tickets:
    build: ./tickets
    ports:
      - "3003:3000"
    depends_on:
      - database
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME} 
  reports:
    build: ./reports
    ports:
      - "3004:3000"
    depends_on:
      - database
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME} 
    restart: always
  notifications:
    build: ./notifications
    ports:
      - "3005:3000"
    depends_on:
      - database
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME} 
