version:  "3"
services:
  database:
    image: mysql:latest
    ports:
      - "3308:3306"
    volumes: 
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: osi2022
      MYSQL_DATABASE: mysql
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: always