version:  "3"
services:
  database:
    image: mysql:latest
    ports:
      - "3308:3306"
    volumes: 
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: osi2022
      MYSQL_DATABASE: mysql
  api:
    build: ./api
    ports:
      - "3001:3000"
    depends_on:
      - database
    restart: always
  users:
    build: ./users
    ports:
      - "3002:3000"
    depends_on:
      - database
    restart: always
  tickets:
    build: ./tickets
    ports:
      - "3003:3000"
    depends_on:
      - database
    restart: always
  reports:
    build: ./reports
    ports:
      - "3004:3000"
    depends_on:
      - database
    restart: always
  notifications:
    build: ./notifications
    ports:
      - "3005:3000"
    depends_on:
      - database
    restart: always