-- MySQL Script generated by MySQL Workbench
-- Thu Dec 29 09:07:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OSI_1.04
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `OSI_1.04` ;

-- -----------------------------------------------------
-- Schema OSI_1.04
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OSI_1.04` DEFAULT CHARACTER SET utf8 ;
USE `OSI_1.04` ;

-- -----------------------------------------------------
-- Table `OSI_1.04`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`user` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`user` (
  `iduser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(130) NOT NULL,
  `deleted` TINYINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `user_type` TINYINT(1) NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`driver` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`driver` (
  `iddriver` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT UNSIGNED NOT NULL,
  `suspended` TINYINT NULL,
  PRIMARY KEY (`iddriver`, `iduser`),
  UNIQUE INDEX `iddriver_UNIQUE` (`iddriver` ASC) ,
  INDEX `fk_driver_user1_idx` (`iduser` ASC) ,
  CONSTRAINT `fk_driver_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `OSI_1.04`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`passenger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`passenger` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`passenger` (
  `idpassenger` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT UNSIGNED NOT NULL,
  `suspended` TINYINT NULL,
  PRIMARY KEY (`idpassenger`, `iduser`),
  UNIQUE INDEX `idpassenger_UNIQUE` (`idpassenger` ASC) ,
  INDEX `fk_passenger_user1_idx` (`iduser` ASC) ,
  CONSTRAINT `fk_passenger_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `OSI_1.04`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`bus_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`bus_class` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`bus_class` (
  `idbus_class` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(500) NULL,
  `price_coefficient` DECIMAL(4,2) NOT NULL,
  `deleted` TINYINT NULL,
  PRIMARY KEY (`idbus_class`),
  UNIQUE INDEX `idbus_class_UNIQUE` (`idbus_class` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`bus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`bus` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`bus` (
  `idbus` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `seats` INT NOT NULL,
  `is_working` TINYINT NULL,
  `carrier` VARCHAR(45) NULL,
  `idbus_class` INT NOT NULL,
  PRIMARY KEY (`idbus`, `idbus_class`),
  INDEX `fk_bus_bus_class1_idx` (`idbus_class` ASC) ,
  CONSTRAINT `fk_bus_bus_class1`
    FOREIGN KEY (`idbus_class`)
    REFERENCES `OSI_1.04`.`bus_class` (`idbus_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`station` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`station` (
  `idstation` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NULL,
  PRIMARY KEY (`idstation`),
  UNIQUE INDEX `idstation_UNIQUE` (`idstation` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`distance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`distance` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`distance` (
  `idstation` INT NOT NULL,
  `idstation2` INT NOT NULL,
  `distance` DECIMAL(4,2) NOT NULL,
  `time_estimate` DECIMAL(4,2) NULL,
  PRIMARY KEY (`idstation`, `idstation2`),
  INDEX `fk_station_has_station_station2_idx` (`idstation2` ASC) ,
  INDEX `fk_station_has_station_station1_idx` (`idstation` ASC) ,
  CONSTRAINT `fk_station_has_station_station1`
    FOREIGN KEY (`idstation`)
    REFERENCES `OSI_1.04`.`station` (`idstation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_station_has_station_station2`
    FOREIGN KEY (`idstation2`)
    REFERENCES `OSI_1.04`.`station` (`idstation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`route` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`route` (
  `idroute` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(4,2) NOT NULL,
  `repeat` INT NULL,
  `time` TIMESTAMP NOT NULL,
  `duration` DECIMAL(4,2) NULL,
  `tickets_sold` INT NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`idroute`),
  UNIQUE INDEX `idroute_UNIQUE` (`idroute` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`report` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`report` (
  `idreport` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NOT NULL,
  `time` TIMESTAMP NOT NULL,
  `idroute` INT NOT NULL,
  `url` VARCHAR(100) NULL,
  PRIMARY KEY (`idreport`, `idroute`),
  UNIQUE INDEX `idreport_UNIQUE` (`idreport` ASC) ,
  INDEX `fk_report_route1_idx` (`idroute` ASC) ,
  CONSTRAINT `fk_report_route1`
    FOREIGN KEY (`idroute`)
    REFERENCES `OSI_1.04`.`route` (`idroute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`ticket` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`ticket` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `base_price` DECIMAL(4,2) NOT NULL,
  `luggage` INT NULL,
  `idpassenger` INT NOT NULL,
  PRIMARY KEY (`idticket`, `idpassenger`),
  UNIQUE INDEX `idticket_UNIQUE` (`idticket` ASC) ,
  INDEX `fk_ticket_passenger1_idx` (`idpassenger` ASC) ,
  CONSTRAINT `fk_ticket_passenger1`
    FOREIGN KEY (`idpassenger`)
    REFERENCES `OSI_1.04`.`passenger` (`idpassenger`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`route_has_driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`route_has_driver` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`route_has_driver` (
  `idroute` INT NOT NULL,
  `iddriver` INT NOT NULL,
  PRIMARY KEY (`idroute`, `iddriver`),
  INDEX `fk_route_has_driver_driver1_idx` (`iddriver` ASC) ,
  INDEX `fk_route_has_driver_route1_idx` (`idroute` ASC) ,
  CONSTRAINT `fk_route_has_driver_route1`
    FOREIGN KEY (`idroute`)
    REFERENCES `OSI_1.04`.`route` (`idroute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_has_driver_driver1`
    FOREIGN KEY (`iddriver`)
    REFERENCES `OSI_1.04`.`driver` (`iddriver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`route_has_bus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`route_has_bus` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`route_has_bus` (
  `idroute` INT NOT NULL,
  `idbus` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idroute`, `idbus`),
  INDEX `fk_route_has_bus_bus1_idx` (`idbus` ASC) ,
  INDEX `fk_route_has_bus_route1_idx` (`idroute` ASC) ,
  CONSTRAINT `fk_route_has_bus_route1`
    FOREIGN KEY (`idroute`)
    REFERENCES `OSI_1.04`.`route` (`idroute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_has_bus_bus1`
    FOREIGN KEY (`idbus`)
    REFERENCES `OSI_1.04`.`bus` (`idbus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`discounts` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`discounts` (
  `iddiscounts` INT NOT NULL AUTO_INCREMENT,
  `min_age` INT NOT NULL,
  `max_age` INT NOT NULL,
  `coefficient` DECIMAL(4,2) NOT NULL,
  `deletede` TINYINT NULL,
  PRIMARY KEY (`iddiscounts`),
  UNIQUE INDEX `iddiscounts_UNIQUE` (`iddiscounts` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`route_has_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`route_has_ticket` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`route_has_ticket` (
  `idroute` INT NOT NULL,
  `idticket` INT NOT NULL,
  `idpassenger` INT NOT NULL,
  PRIMARY KEY (`idroute`, `idticket`, `idpassenger`),
  INDEX `fk_route_has_ticket_ticket1_idx` (`idticket` ASC, `idpassenger` ASC) ,
  INDEX `fk_route_has_ticket_route1_idx` (`idroute` ASC) ,
  CONSTRAINT `fk_route_has_ticket_route1`
    FOREIGN KEY (`idroute`)
    REFERENCES `OSI_1.04`.`route` (`idroute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_has_ticket_ticket1`
    FOREIGN KEY (`idticket` , `idpassenger`)
    REFERENCES `OSI_1.04`.`ticket` (`idticket` , `idpassenger`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`route_has_discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`route_has_discounts` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`route_has_discounts` (
  `idroute` INT NOT NULL,
  `iddiscounts` INT NOT NULL,
  PRIMARY KEY (`idroute`, `iddiscounts`),
  INDEX `fk_route_has_discounts_discounts1_idx` (`iddiscounts` ASC) ,
  INDEX `fk_route_has_discounts_route1_idx` (`idroute` ASC) ,
  CONSTRAINT `fk_route_has_discounts_route1`
    FOREIGN KEY (`idroute`)
    REFERENCES `OSI_1.04`.`route` (`idroute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_has_discounts_discounts1`
    FOREIGN KEY (`iddiscounts`)
    REFERENCES `OSI_1.04`.`discounts` (`iddiscounts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`station_has_route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`station_has_route` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`station_has_route` (
  `idstation` INT NOT NULL,
  `idroute` INT NOT NULL,
  `order` INT NOT NULL,
  PRIMARY KEY (`idstation`, `idroute`),
  INDEX `fk_station_has_route_route1_idx` (`idroute` ASC) ,
  INDEX `fk_station_has_route_station1_idx` (`idstation` ASC) ,
  CONSTRAINT `fk_station_has_route_station1`
    FOREIGN KEY (`idstation`)
    REFERENCES `OSI_1.04`.`station` (`idstation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_station_has_route_route1`
    FOREIGN KEY (`idroute`)
    REFERENCES `OSI_1.04`.`route` (`idroute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.04`.`bank_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.04`.`bank_account` ;

CREATE TABLE IF NOT EXISTS `OSI_1.04`.`bank_account` (
  `idpassenger` INT NOT NULL,
  `iduser` INT UNSIGNED NOT NULL,
  `balance` DECIMAL(6,2) NULL,
  PRIMARY KEY (`idpassenger`, `iduser`),
  CONSTRAINT `fk_bank_account_passenger1`
    FOREIGN KEY (`idpassenger` , `iduser`)
    REFERENCES `OSI_1.04`.`passenger` (`idpassenger` , `iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- SET SQL_SAFE_UPDATES = 0;
-- UPDATE mysql.user SET host='%' WHERE user='root';
-- FLUSH PRIVILEGES;

INSERT INTO `OSI_1.04`.`user` (`username`, `password`, `deleted`, `name`, `user_type`) VALUES ('admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', '0', 'Admin', '0');
INSERT INTO `OSI_1.04`.`user` (`username`, `password`, `deleted`, `name`, `user_type`) VALUES ('driver', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', '0', 'Driver', '1');
INSERT INTO `OSI_1.04`.`user` (`username`, `password`, `deleted`, `name`, `user_type`) VALUES ('passenger', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', '0', 'Passenger', '2');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
