-- MySQL Script generated by MySQL Workbench
-- Wed Dec 28 09:15:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OSI_1.02
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `OSI_1.02` ;

-- -----------------------------------------------------
-- Schema OSI_1.02
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OSI_1.02` DEFAULT CHARACTER SET utf8 ;
USE `OSI_1.02` ;

-- -----------------------------------------------------
-- Table `OSI_1.02`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`user` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`user` (
  `iduser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `user_type` TINYINT(1) NOT NULL DEFAULT 2,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`driver` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`driver` (
  `iddriver` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT UNSIGNED NOT NULL,
  `suspended` TINYINT NULL,
  PRIMARY KEY (`iddriver`, `iduser`),
  UNIQUE INDEX `iddriver_UNIQUE` (`iddriver` ASC) VISIBLE,
  INDEX `fk_driver_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_driver_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `OSI_1.02`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`passenger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`passenger` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`passenger` (
  `idpassenger` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT UNSIGNED NOT NULL,
  `suspended` TINYINT NULL,
  PRIMARY KEY (`idpassenger`, `iduser`),
  UNIQUE INDEX `idpassenger_UNIQUE` (`idpassenger` ASC) VISIBLE,
  INDEX `fk_passenger_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_passenger_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `OSI_1.02`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`bus_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`bus_class` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`bus_class` (
  `idbus_class` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(500) NULL,
  `price_coefficient` DECIMAL(4,2) NOT NULL,
  `deleted` TINYINT NULL,
  PRIMARY KEY (`idbus_class`),
  UNIQUE INDEX `idbus_class_UNIQUE` (`idbus_class` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`bus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`bus` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`bus` (
  `idbus` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `seats` INT NOT NULL,
  `is_working` TINYINT NULL,
  `carrier` VARCHAR(45) NULL,
  `idbus_class` INT NOT NULL,
  PRIMARY KEY (`idbus`, `idbus_class`),
  INDEX `fk_bus_bus_class1_idx` (`idbus_class` ASC) VISIBLE,
  CONSTRAINT `fk_bus_bus_class1`
    FOREIGN KEY (`idbus_class`)
    REFERENCES `OSI_1.02`.`bus_class` (`idbus_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`station` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`station` (
  `idstation` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `deleted` TINYINT NULL,
  PRIMARY KEY (`idstation`),
  UNIQUE INDEX `idstation_UNIQUE` (`idstation` ASC) VISIBLE,
  UNIQUE INDEX `country_UNIQUE` (`country` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`distance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`distance` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`distance` (
  `idstation` INT NOT NULL,
  `idstation2` INT NOT NULL,
  `distance` DECIMAL(4,2) NOT NULL,
  `time_estimate` DECIMAL(4,2) NULL,
  PRIMARY KEY (`idstation`, `idstation2`),
  INDEX `fk_station_has_station_station2_idx` (`idstation2` ASC) VISIBLE,
  INDEX `fk_station_has_station_station1_idx` (`idstation` ASC) VISIBLE,
  CONSTRAINT `fk_station_has_station_station1`
    FOREIGN KEY (`idstation`)
    REFERENCES `OSI_1.02`.`station` (`idstation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_station_has_station_station2`
    FOREIGN KEY (`idstation2`)
    REFERENCES `OSI_1.02`.`station` (`idstation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`route` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`route` (
  `idroute` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(4,2) NOT NULL,
  `repeat` INT NULL,
  `time` TIMESTAMP NOT NULL,
  `duration` DECIMAL(4,2) NULL,
  `routecol` VARCHAR(45) NULL,
  `active` TINYINT NULL,
  `tickets_sold` INT NULL,
  PRIMARY KEY (`idroute`),
  UNIQUE INDEX `idroute_UNIQUE` (`idroute` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`report` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`report` (
  `idreport` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NOT NULL,
  `time` TIMESTAMP NOT NULL,
  `idroute` INT NOT NULL,
  PRIMARY KEY (`idreport`, `idroute`),
  UNIQUE INDEX `idreport_UNIQUE` (`idreport` ASC) VISIBLE,
  INDEX `fk_report_route1_idx` (`idroute` ASC) VISIBLE,
  CONSTRAINT `fk_report_route1`
    FOREIGN KEY (`idroute`)
    REFERENCES `OSI_1.02`.`route` (`idroute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`ticket` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`ticket` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `base_price` DECIMAL(4,2) NOT NULL,
  `luggage` INT NULL,
  `idpassenger` INT NOT NULL,
  PRIMARY KEY (`idticket`, `idpassenger`),
  UNIQUE INDEX `idticket_UNIQUE` (`idticket` ASC) VISIBLE,
  INDEX `fk_ticket_passenger1_idx` (`idpassenger` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_passenger1`
    FOREIGN KEY (`idpassenger`)
    REFERENCES `OSI_1.02`.`passenger` (`idpassenger`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`route_has_driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`route_has_driver` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`route_has_driver` (
  `idroute` INT NOT NULL,
  `iddriver` INT NOT NULL,
  PRIMARY KEY (`idroute`, `iddriver`),
  INDEX `fk_route_has_driver_driver1_idx` (`iddriver` ASC) VISIBLE,
  INDEX `fk_route_has_driver_route1_idx` (`idroute` ASC) VISIBLE,
  CONSTRAINT `fk_route_has_driver_route1`
    FOREIGN KEY (`idroute`)
    REFERENCES `OSI_1.02`.`route` (`idroute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_has_driver_driver1`
    FOREIGN KEY (`iddriver`)
    REFERENCES `OSI_1.02`.`driver` (`iddriver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`route_has_bus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`route_has_bus` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`route_has_bus` (
  `idroute` INT NOT NULL,
  `idbus` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idroute`, `idbus`),
  INDEX `fk_route_has_bus_bus1_idx` (`idbus` ASC) VISIBLE,
  INDEX `fk_route_has_bus_route1_idx` (`idroute` ASC) VISIBLE,
  CONSTRAINT `fk_route_has_bus_route1`
    FOREIGN KEY (`idroute`)
    REFERENCES `OSI_1.02`.`route` (`idroute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_has_bus_bus1`
    FOREIGN KEY (`idbus`)
    REFERENCES `OSI_1.02`.`bus` (`idbus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`discounts` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`discounts` (
  `iddiscounts` INT NOT NULL AUTO_INCREMENT,
  `min_age` INT NOT NULL,
  `max_age` INT NOT NULL,
  `coefficient` DECIMAL(4,2) NOT NULL,
  `deletede` TINYINT NULL,
  PRIMARY KEY (`iddiscounts`),
  UNIQUE INDEX `iddiscounts_UNIQUE` (`iddiscounts` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`route_has_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`route_has_ticket` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`route_has_ticket` (
  `idroute` INT NOT NULL,
  `idticket` INT NOT NULL,
  `idpassenger` INT NOT NULL,
  PRIMARY KEY (`idroute`, `idticket`, `idpassenger`),
  INDEX `fk_route_has_ticket_ticket1_idx` (`idticket` ASC, `idpassenger` ASC) VISIBLE,
  INDEX `fk_route_has_ticket_route1_idx` (`idroute` ASC) VISIBLE,
  CONSTRAINT `fk_route_has_ticket_route1`
    FOREIGN KEY (`idroute`)
    REFERENCES `OSI_1.02`.`route` (`idroute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_has_ticket_ticket1`
    FOREIGN KEY (`idticket` , `idpassenger`)
    REFERENCES `OSI_1.02`.`ticket` (`idticket` , `idpassenger`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`route_has_discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`route_has_discounts` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`route_has_discounts` (
  `idroute` INT NOT NULL,
  `iddiscounts` INT NOT NULL,
  PRIMARY KEY (`idroute`, `iddiscounts`),
  INDEX `fk_route_has_discounts_discounts1_idx` (`iddiscounts` ASC) VISIBLE,
  INDEX `fk_route_has_discounts_route1_idx` (`idroute` ASC) VISIBLE,
  CONSTRAINT `fk_route_has_discounts_route1`
    FOREIGN KEY (`idroute`)
    REFERENCES `OSI_1.02`.`route` (`idroute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_has_discounts_discounts1`
    FOREIGN KEY (`iddiscounts`)
    REFERENCES `OSI_1.02`.`discounts` (`iddiscounts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OSI_1.02`.`station_has_route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OSI_1.02`.`station_has_route` ;

CREATE TABLE IF NOT EXISTS `OSI_1.02`.`station_has_route` (
  `idstation` INT NOT NULL,
  `idroute` INT NOT NULL,
  `order` INT NOT NULL,
  PRIMARY KEY (`idstation`, `idroute`),
  INDEX `fk_station_has_route_route1_idx` (`idroute` ASC) VISIBLE,
  INDEX `fk_station_has_route_station1_idx` (`idstation` ASC) VISIBLE,
  CONSTRAINT `fk_station_has_route_station1`
    FOREIGN KEY (`idstation`)
    REFERENCES `OSI_1.02`.`station` (`idstation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_station_has_route_route1`
    FOREIGN KEY (`idroute`)
    REFERENCES `OSI_1.02`.`route` (`idroute`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
